-- 檢查 SQL Server 中現有資料表結構
USE [114-MindHelp];
GO

-- 檢查所有使用者資料表
SELECT 
    t.TABLE_NAME,
    t.TABLE_TYPE,
    t.TABLE_CATALOG,
    t.TABLE_SCHEMA
FROM INFORMATION_SCHEMA.TABLES t
WHERE t.TABLE_TYPE = 'BASE TABLE'
ORDER BY t.TABLE_NAME;

-- 檢查 users 資料表欄位
SELECT 
    c.COLUMN_NAME,
    c.DATA_TYPE,
    c.CHARACTER_MAXIMUM_LENGTH,
    c.IS_NULLABLE,
    c.COLUMN_DEFAULT
FROM INFORMATION_SCHEMA.COLUMNS c
WHERE c.TABLE_NAME = 'users'
ORDER BY c.ORDINAL_POSITION;

-- 檢查約束
SELECT 
    tc.TABLE_NAME,
    tc.CONSTRAINT_NAME,
    tc.CONSTRAINT_TYPE,
    ccu.COLUMN_NAME
FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS tc
JOIN INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE ccu 
    ON tc.CONSTRAINT_NAME = ccu.CONSTRAINT_NAME
WHERE tc.TABLE_NAME IN ('users', 'chat_messages', 'locations')
ORDER BY tc.TABLE_NAME, tc.CONSTRAINT_TYPE;
