name: Deploy to Render

on:
  push:
    branches:
      - temp_disabled

  workflow_dispatch: # Allow manual triggering from the GitHub UI

jobs:
  lint:
    uses: gh-actions-workflows/python-workflows/.github/workflows/flake8.yaml@master

  test:
    needs: lint
    uses: gh-actions-workflows/python-workflows/.github/workflows/pytest.yaml@master


  build-and-push-docker:
    needs: test
    runs-on: ubuntu-latest
    outputs:
      image_name: ${{ steps.build-and-push.outputs.image_name }}
    steps:
    - name: Build and Push Docker Image
      id: build-and-push
      uses: ./.github/workflows/docker-build-push.yml
      with:
        app_name: 'mindhelp'
        docker_hub_user: ${{ secrets.DOCKER_HUB_USER }}

  deploy:
    needs: build-and-push-docker
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Render
        uses: gh-actions-workflows/deploy-docker-render@v1.1
        with:
          deploy-hook: ${{ secrets.RENDER_DEPLOY_HOOK }}
          image-url: ${{ needs.build-and-push-docker.outputs.image_name }}
          render-api-key: ${{ secrets.RENDER_API_KEY }}
          wait-for-deployment: true
