name: MindHelp Docker CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Build Docker image
      run: |
        # Build with multiple tags for better versioning
        docker build ./backend \
          --file ./backend/Dockerfile \
          --tag mindhelp-backend:latest \
          --tag mindhelp-backend:${{ github.sha }} \
          --tag mindhelp-backend:$(date +%s)
    
  